server:
  port: 9099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: MEALPLANS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mealplansdb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect